### ISSUE TITLE
How exactly I may use sealedbox.web.js?

### ISSUE THREAD

**Issue by SilentImp** [whs/tweetnacl-sealed-box#2]
Hi, I need to create an isomorphic application, bundled with Webpack.
How exactly I should use `sealedbox.web.js` for the browser?
If I try to do this:

```
import utils from 'tweetnacl-util';
import tweetnacl from 'tweetnacl';
import sealedboxnode from 'tweetnacl-sealedbox-js/sealedbox.node';
import sealedboxweb from 'tweetnacl-sealedbox-js/sealedbox.web';

const sealedbox = process.browser ? sealedboxweb : sealedboxnode;
tweetnacl.sealedbox = sealedboxnode;
tweetnacl.utils = utils;
```

I am getting an errors:
```
Cannot find module 'nacl' from 'sealedbox.web.js'
Module not found: Can't resolve 'Object' in '/project/node_modules/tweetnacl-sealedbox-js'
```

What has gone wrong?

**Comment by whs** [comment]
The .web file is a precompiled file when you can't use/don't want to use webpack. Since you're probably using webpack, you can just import 'tweetnacl-sealedbox-js' and start using it.

**Comment by SilentImp** [comment]
@whs Thanks, got it, but that's how I have used it from the start.

```
import utils from 'tweetnacl-util';
import tweetnacl from 'tweetnacl';
import sealedbox from 'tweetnacl-sealedbox-js';
import { ENCRYPT_PUBLIC } from 'constants/env';

tweetnacl.sealedbox = sealedbox;
tweetnacl.utils = utils;

const encrypt = data => {
  const stringifiedData = JSON.stringify(data);
  const buffer = tweetnacl.utils.decodeUTF8(stringifiedData);
  return tweetnacl.sealedbox.seal(buffer, ENCRYPT_PUBLIC);
};
```

And `tweetnacl.sealedbox` is equal `undefined` in this case.
But only in the browser.
In the node.js it's fine.

**Comment by SilentImp** [comment]
Aha, look like a problem with import.

```
const sealedbox = require('tweetnacl-sealedbox-js');
console.log('sealedbox:', sealedbox);
// node: 
// sealedbox: { overheadLength: [Getter], seal: [Getter], open: [Getter] }
// web: 
// sealedbox: Module {__esModule: true, Symbol(Symbol.toStringTag): "Module"}
```

**Comment by SilentImp** [comment]
Looks like it works with require and doesn't work with import.
```
./src/utils/report.js
Attempted import error: 'tweetnacl-sealedbox-js' does not contain a default export (imported as 'sealedbox').

```

**Comment by SilentImp** [comment]
But it works this way:
```
import { seal, open } from 'tweetnacl-sealedbox-js';
const sealedbox = {
  seal,
  open,
};
tweetnacl.sealedbox = sealedbox;
tweetnacl.utils = utils;
```

**Comment by SilentImp** [comment]
I'd say
```
export * from './src/consts';

import seal from './src/seal';
import open from './src/open';

export default {
  seal, open
}
export {seal, open};
```
in the `entrypoint.js` may help, but give me a moment, I will test it and make PR.

**Comment by SilentImp** [comment]
@whs looks like I have a hard time building libsodium on mac.

```
$ npm i

> sodium@2.0.3 preinstall  /tweetnacl-sealed-box/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /tweetnacl-sealed-box/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: libtoolize --copy --force
Can't exec "libtoolize": No such file or directory at /usr/local/share/autoconf/Autom4te/FileUtils.pm line 345, <GEN2> line 5.
autoreconf: failed to run libtoolize: No such file or directory
autoreconf: libtoolize is needed because this package uses Libtool
make: *** [libsodium] Error 1
/tweetnacl-sealed-box/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/tweetnacl-sealed-box/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

so I can't make a PR at last in the nearest couple of hours.
If you can add this change by yourselt it would be great.

**Comment by whs** [comment]
Can you try `brew install libsodium` then reinstall npm? Otherwise, I think this library works fine without sodium module. It is only used in testing to ensure compatibility

**Comment by SilentImp** [comment]
@whs done, successfully, but `npm i` still failing:

```
$ npm i

> sodium@2.0.3 preinstall /tweetnacl-sealed-box/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /tweetnacl-sealed-box/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: libtoolize --copy --force
Can't exec "libtoolize": No such file or directory at /usr/local/share/autoconf/Autom4te/FileUtils.pm line 345, <GEN2> line 5.
autoreconf: failed to run libtoolize: No such file or directory
autoreconf: libtoolize is needed because this package uses Libtool
make: *** [libsodium] Error 1
/tweetnacl-sealed-box/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/tweetnacl-sealed-box/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
npm WARN tweetnacl-sealedbox-js@1.1.0 No repository field.


$ tweetnacl-sealed-box silentimp$ brew install Libtool
Warning: libtool 2.4.6_1 is already installed and up-to-date
To reinstall 2.4.6_1, run `brew reinstall libtool`
```

**Comment by whs** [comment]
brew install libsodium not libtool

**Comment by SilentImp** [comment]
@whs yes, i have done `brew install libsodium` before `$npm i`.
```
$ brew install libsodium
Warning: libsodium 1.0.18 is already installed and up-to-date
To reinstall 1.0.18, run `brew reinstall libsodium`
```
hm … actually, it looks like it can't be found. maybe it's kinda path issue.
but it looks for libsodium inside `/node_modules/`

/tweetnacl-sealed-box/node_modules/sodium/deps/build/lib/libsodium

**Comment by SilentImp** [comment]
it's located in
```
$ locate libsodium
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libsodium.rb
```
